# Generated by Django 3.2.5 on 2023-02-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_studentbulkupload_csv_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentbulkupload',
            options={'ordering': ['firstname', 'other_name']},
        ),
        migrations.AddField(
            model_name='studentbulkupload',
            name='firstname',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentbulkupload',
            name='other_name',
            field=models.TextField(blank=True),
        ),
    ]
