# Generated by Django 4.1.2 on 2023-02-04 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_sale'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
